name: Build tests
on:
  schedule:
    # Runs at 3:00 AM UTC every day
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      machine:
        description: 'Select machine'
        required: true
        type: choice
        options:
          - raspberrypi3-mesa
          - raspberrypi4-64-mesa
          - raspberrypi5
          - wandboard-mesa
      wpe_vers:
        description: 'Select WPEWebKit version'
        required: true
        type: choice
        options:
          - 2_50
          - nightly

jobs:
  scarthgap-repo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'scarthgap'

  buildhistory-collect-srcrevs:
    strategy:
      fail-fast: false
      matrix:
        machine: ${{ inputs.machine != '' && inputs.machine || ['raspberrypi3-mesa', 'raspberrypi5'] }}
        wpe_vers: ${{ inputs.wpe_vers != '' && inputs.wpe_vers || ['nightly'] }}
        yocto_rel: ['scarthgap']
    continue-on-error: true
    runs-on: ubuntu-22.04
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/buildhistory-collect-srcrevs
        env:
          S3_STORAGE: ${{ secrets.S3_STORAGE }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.buildhistory.wpe-${{ matrix.wpe_vers }} --update-config'
          s3_storage: ${S3_STORAGE}
          repo_release: ${{ matrix.yocto_rel }}

  build:
    strategy:
      fail-fast: false
      matrix:
        machine: ${{ inputs.machine != '' && inputs.machine || ['raspberrypi3-mesa', 'raspberrypi5'] }}
        wpe_vers: ${{ inputs.wpe_vers != '' && inputs.wpe_vers || ['nightly'] }}
        yocto_rel: ['scarthgap']
    continue-on-error: true
    runs-on: [self-hosted, builder]
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/bitbake-build
        env:
          S3_STORAGE: ${{ secrets.S3_STORAGE }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.reproducible-core.wpe-${{ matrix.wpe_vers }} --update-config'
          s3_storage: ${S3_STORAGE}
          repo_release: ${{ matrix.yocto_rel }}

  test:
    strategy:
      fail-fast: false
      matrix:
        machine: ${{ inputs.machine != '' && inputs.machine || ['raspberrypi3-mesa', 'raspberrypi5'] }}
        wpe_vers: ${{ inputs.wpe_vers != '' && inputs.wpe_vers || ['nightly'] }}
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, podman]
    permissions:
      pull-requests: write
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/podman-robot
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          S3_STORAGE: ${{ secrets.S3_STORAGE }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          github_token: ${GITHUB_TOKEN}
          s3_storage: ${S3_STORAGE}
          wpe_vers: ${{ matrix.wpe_vers }}
