name: Build tests raspberrypi3-mesa nightly manually
on: workflow_dispatch

jobs:
  scarthgap-repo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/bitbake-repo
        with:
          repo_release: 'scarthgap'

  build-raspberrypi3-mesa-nightly:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi3-mesa']
        wpe_vers: ['nightly']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, builder]
    needs: scarthgap-repo
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/bitbake-build
        env:
          S3_STORAGE: ${{ secrets.S3_STORAGE }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          bitbake_source: 'poky-wayland layers.raspberrypi conf.reproducible-core.wpe-${{ matrix.wpe_vers }} --update-config'
          repo_release: ${{ matrix.yocto_rel }}
          s3_storage: ${S3_STORAGE}

  test-raspberrypi3-mesa-nightly:
    strategy:
      fail-fast: false
      matrix:
        machine: ['raspberrypi3-mesa']
        wpe_vers: ['nightly']
        yocto_rel: ['scarthgap']
    runs-on: [self-hosted, podman]
    permissions:
      pull-requests: write
    needs: build-raspberrypi3-mesa-nightly
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/s3-configure
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_HOST_BASE: ${{ secrets.S3_HOST_BASE }}
        with:
          access_key: ${S3_ACCESS_KEY}
          secret_key: ${S3_SECRET_KEY}
          host_base: ${S3_HOST_BASE}
      - uses: ./.github/actions/podman-robot
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          S3_STORAGE: ${{ secrets.S3_STORAGE }}
        with:
          bitbake_buildname: wpe-${{ matrix.wpe_vers }}-${{ matrix.machine }}
          bitbake_machine: ${{ matrix.machine }}
          github_token: ${GITHUB_TOKEN}
          s3_storage: ${S3_STORAGE}
          wpe_vers: ${{ matrix.wpe_vers }}
